name: "Build and Test"
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: gradlew build
      run: ./gradlew build
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: reports
        path: build/reports